spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/axonproject
    username: postgres
    password: yasuo20gg
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL

